import Head from 'next/head';
import { Navigation } from '../../components/Utils/Navigation';
import { TopBar } from '../../components/Utils/TopBar';
import { VideoPlayer } from '../../components/VideoContentPage/VideoPlayer';
import { VideoPlayList } from '../../components/VideoContentPage/VideoPlayList';
import { LContainer, LHeader, LLeftCol, LMain, LRightCol, LSlot } from '../../layouts/';

export default function VideoContentPage() {
  return (
    <div>
      <Head>
        <title>中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain size="large">
        <LContainer>
          <LLeftCol>
            <LSlot>
              <VideoPlayer />
            </LSlot>
          </LLeftCol>
          <LRightCol>
            <LSlot>
              <VideoPlayList />
            </LSlot>
          </LRightCol>
        </LContainer>
      </LMain>
    </div>
  );
}
