import Head from 'next/head';
import { Footer } from '../../components/Utils/Footer';
import { Navigation } from '../../components/Utils/Navigation';
import { VideoIntroductionBox } from '../../components/VideoContentPage/VideoIntroductionBox';
import { VideoPlayer } from '../../components/VideoContentPage/VideoPlayer';
import { VideoPlayList } from '../../components/VideoContentPage/VideoPlayList';
import { VideoContentLayout } from '../../layouts/VideoContentLayout';
const LHeader = VideoContentLayout.Header;
const LMain = VideoContentLayout.Main;
const LFooter = VideoContentLayout.Footer;
const LLanding = VideoContentLayout.Landing;
const LContainer = VideoContentLayout.Container;
const LLeftCol = VideoContentLayout.LeftCol;
const LRightCol = VideoContentLayout.RightCol;
const LSlot = VideoContentLayout.Slot;

export default function VideoContentPage() {
  return (
    <div>
      <Head>
        <title>中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LContainer>
          <LLeftCol>
            <LSlot>
              <VideoPlayer />
              
            </LSlot>
            <LSlot>
              <VideoIntroductionBox />
            </LSlot>
          </LLeftCol>
          <LRightCol>
            <LSlot>
              <VideoPlayList />
            </LSlot>
          </LRightCol>
        </LContainer>
      </LMain>
    </div>
  );
}
