import Head from 'next/head';
import { ColumnNewsList } from '../../components/ColumnIndexPage/components/ColumnNewsList';
import { Footer } from '../../components/Common/Footer';
import { Navigation } from '../../components/Common/Navigation';
import { ScrollToTop } from '../../components/Common/ScrollToTop';
import { TopBar } from '../../components/Common/TopBar';
import { LFooter, LHeader, LLanding, LMain } from '../../layouts';

export default function ColumnIndexPageTemplate() {
  return (
    <div>
      <Head>
        <title>所有专栏 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <ColumnNewsList />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
