import Head from 'next/head';
import { ResourceClosed } from '../../components/ErrorPage/ResourceClosed';
import { Footer } from '../../components/Common/Footer';
import { Navigation } from '../../components/Common/Navigation';
import { ScrollToTop } from '../../components/Common/ScrollToTop';
import { TopBar } from '../../components/Common/TopBar';
import { LContainer, LFooter, LHeader, LLanding, LLeftCol, LMain, LRightCol } from '../../layouts';
export default function ResourceClosedPage() {
  return (
    <div>
      <Head>
        <title>内容已关闭 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LContainer>
          <ResourceClosed />
        </LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
