import Footer from '@arco-design/web-react/es/Layout/footer';
import Head from 'next/head';
import { LContainer, LFooter, LHeader, LMain } from '../../layouts';
import { Navigation, ScrollToTop, TopBar } from 'views/Common';
import { ResourceClosed } from 'views/ErrorPage/components/ResourceClosed';

export default function ResourceClosedPage() {
  return (
    <div>
      <Head>
        <title>内容已关闭 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LContainer>
          <ResourceClosed />
        </LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
