import Head from 'next/head';
import { BooksShowBox } from 'views/HomePage/components/BooksShowBox';
import { HomePageDebugData } from '@debug/HomePage';
import { LContainer, LFooter, LHeader, LLeftCol, LMain, LRightCol, LSlot, LStickySlot } from '@layouts/index';
import { Footer, Navigation, PictureBox, ScrollToTop, TopBar, TopicBox } from 'views/Common';
import { ArticleNextListBox, ArticleReader } from './components';

export const ArticleContentPageTemplate = () => {
  return (
    <div>
      <Head>
        <title>中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LContainer>
          <LLeftCol>
            <LSlot>
              <ArticleReader />
            </LSlot>
            <LSlot></LSlot>
          </LLeftCol>
          <LRightCol>
            <LSlot>
              <PictureBox data={HomePageDebugData.leftBottomPictureBoxData}></PictureBox>
            </LSlot>
            <LSlot>
              <BooksShowBox data={HomePageDebugData.booksShowBoxData} />
            </LSlot>
            <LSlot>
              <TopicBox />
            </LSlot>
            <LStickySlot>
              <ArticleNextListBox data={HomePageDebugData.hotListBoxData} />
            </LStickySlot>
          </LRightCol>
        </LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
};
