import Footer from '@arco-design/web-react/es/Layout/footer';
import Head from 'next/head';
import { ArticleNextListBox } from './components/ArticleNextListBox';
import { ArticleReader } from './components/ArticleReader';
import { BooksShowBox } from 'views/HomePage/components/BooksShowBox';
import { HomePageDebugData } from '@debug/HomePage';
import { LContainer, LFooter, LHeader, LLeftCol, LMain, LRightCol, LSlot, LStickySlot } from 'layouts';
import { Navigation } from 'views/Common/Navigation';
import { PictureBox } from 'views/Common/PictureBox';
import { ScrollToTop } from 'views/Common/ScrollToTop';
import { TopBar } from 'views/Common/TopBar';
import { TopicBox } from 'views/Common/TopicBox';

export const ArticleContentPageTemplate = () => {
  return (
    <div>
      <Head>
        <title>中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LContainer>
          <LLeftCol>
            <LSlot>
              <ArticleReader />
            </LSlot>
            <LSlot></LSlot>
          </LLeftCol>
          <LRightCol>
            <LSlot>
              <PictureBox data={HomePageDebugData.leftBottomPictureBoxData}></PictureBox>
            </LSlot>
            <LSlot>
              <BooksShowBox data={HomePageDebugData.booksShowBoxData} />
            </LSlot>
            <LSlot>
              <TopicBox />
            </LSlot>
            <LStickySlot>
              <ArticleNextListBox data={HomePageDebugData.hotListBoxData} />
            </LStickySlot>
          </LRightCol>
        </LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
};
