import Head from 'next/head';
import { Divider } from '@arco-design/web-react';
import { GroupContentArticleList, GroupContentHotList, GroupContentVideoList } from './components';
import { LContainer, LFooter, LHeader, LLanding, LMain } from '@/layouts/index';
import { Footer, Navigation, ScrollToTop, TopBar } from '@/views/Common';

export default function GroupContentPageTemplate() {
  return (
    <>
      <Head>
        <title>河南看点 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <GroupContentHotList />
        </LLanding>
        <Divider />
        <LLanding>
          <GroupContentArticleList />
        </LLanding>
        <Divider />
        <LLanding>
          <GroupContentVideoList />
        </LLanding>
        <LContainer></LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </>
  );
}
