import Head from 'next/head';
import { BooksList } from '../../components/BookPage/BooksList';
import { Footer } from '../../components/Utils/Footer';
import { Navigation } from '../../components/Utils/Navigation';
import { TopBar } from '../../components/Utils/TopBar';
import { LFooter, LHeader, LLanding, LMain } from '../../layouts';

export default function BookPage() {
  return (
    <div>
      <Head>
        <title>所有书刊 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <BooksList />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
    </div>
  );
}
