import Head from 'next/head';
import { LFooter, LHeader, LLanding, LMain } from '@/layouts/index';
import { Footer, Navigation, ScrollToTop, TopBar } from 'views/Common';
import { SearchBox } from './components';
import { useRouter } from 'next/router';

export default function SearchPageTemplate() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>搜索 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <SearchBox searchWord={router.query.word?.toString()} />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
