import { Divider } from '@arco-design/web-react';
import Head from 'next/head';
import { Footer } from '../Common/Footer';
import { Navigation } from '../Common/Navigation';
import { ScrollToTop } from '../Common/ScrollToTop';
import { TopBar } from '../../components/Common/TopBar';
import { GroupContentArticleList } from './components/GroupContentArticleList';
import { LContainer, LFooter, LHeader, LLanding, LMain } from 'layouts';
import { GroupContentHotList } from './components/GroupContentHotList';
import { GroupContentVideoList } from './components/GroupContentVideoList';

export default function GroupContentPageTemplate() {
  return (
    <div>
      <Head>
        <title>河南看点 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <GroupContentHotList />
        </LLanding>
        <Divider />
        <LLanding>
          <GroupContentArticleList />
        </LLanding>
        <Divider />
        <LLanding>
          <GroupContentVideoList />
        </LLanding>
        <LContainer></LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
