import { Divider } from '@arco-design/web-react';
import Head from 'next/head';
import { ColumnContentArticleList } from '../../components/ColumnContentPage/ColumnContentArticleList';
import { ColumnContentVideoList } from '../../components/ColumnContentPage/ColumnContentVideoList';
import { Footer } from '../../components/Utils/Footer';
import { Navigation } from '../../components/Utils/Navigation';
import { ScrollToTop } from '../../components/Utils/ScrollToTop';
import { TopBar } from '../../components/Utils/TopBar';
import { LContainer, LFooter, LHeader, LLanding, LMain } from '../../layouts';

export default function ColumnContentPage() {
  return (
    <div>
      <Head>
        <title>社会 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <ColumnContentArticleList />
        </LLanding>
        <Divider />
        <LLanding>
          <ColumnContentVideoList />
        </LLanding>
        <LContainer></LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
