import Head from 'next/head';
import { SearchBox } from '../../components/SearchPage/SearchBox';
import { Footer } from '../../components/Utils/Footer';
import { Navigation } from '../../components/Utils/Navigation';
import { ScrollToTop } from '../../components/Utils/ScrollToTop';
import { SearchLayout } from '../../layouts/SearchLayout';

const LHeader = SearchLayout.Header;
const LMain = SearchLayout.Main;
const LFooter = SearchLayout.Footer;
const LLanding = SearchLayout.Landing;
const LContainer = SearchLayout.Container;
const LLeftCol = SearchLayout.LeftCol;
const LRightCol = SearchLayout.RightCol;
const LSlot = SearchLayout.Slot;

export default function SearchPage() {
  return (
    <div>
      <Head>
        <title>搜索 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <SearchBox />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
