import Head from 'next/head';
import { useRouter } from 'next/router';
import { SearchBox } from '../../components/SearchPage/SearchBox';
import { Footer } from '../../components/Common/Footer';
import { Navigation } from '../../components/Common/Navigation';
import { ScrollToTop } from '../../components/Common/ScrollToTop';
import { TopBar } from '../../components/Common/TopBar';
import { LFooter, LHeader, LLanding, LMain } from '../../layouts';

export default function SearchPage() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>搜索 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <SearchBox searchWord={router.query.word?.toString()} />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
