import Head from 'next/head';
import { BooksList } from './components';
import { LFooter, LHeader, LLanding, LMain } from '@/layouts/index';
import { Footer, Navigation, TopBar } from 'views/Common';

export default function BookIndexPageTemplate() {
  return (
    <>
      <Head>
        <title>所有书刊 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <BooksList />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
    </>
  );
}
