import Head from "next/head";
import {
  LContainer,
  LHeader,
  LLeftCol,
  LMain,
  LRightCol,
  LSlot,
} from "@/layouts/index";
import { Navigation, TopBar } from "@/views/Common";
import { VideoPlayer, PlayList } from "./components";

export default function VideoContentPageTemplate() {
  return (
    <>
      <Head>
        <title>{}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain size="large">
        <LContainer>
          <LLeftCol>
            <LSlot>
              <VideoPlayer data={undefined} />
            </LSlot>
          </LLeftCol>
          <LRightCol>
            <LSlot>
              <PlayList data={undefined} />
            </LSlot>
          </LRightCol>
        </LContainer>
      </LMain>
    </>
  );
}
