import Head from 'next/head';
import useMemoryMode from '@hooks/useMemoryMode';
import { BooksShowBox, Headline, HomeCarousel, HomePageNewsListBox, SpecialNewsBox } from './components';
import { BooksShowBoxData, HeadlineData, HotListBoxData, PictureBoxData, SpecialNewsBoxData } from '@models/data';
import { Footer, HotListBox, Navigation, PictureBox, ScrollToTop, TopBar, TopicBox } from 'views/Common';
import { GetServerSideProps } from 'next';
import { HomePageDebugData } from '@debug/HomePage';
import { LContainer, LFooter, LHeader, LLanding, LLeftCol, LMain, LRightCol, LSlot } from '@layouts/index';

export interface HomePageServerProps {
  booksShowBoxData: BooksShowBoxData;
  headlineData: HeadlineData;
  hotListBoxData: HotListBoxData;
  leftBottomPictureBoxData: PictureBoxData;
  leftTopPictureBoxData: PictureBoxData;
  specialNewsBoxData: SpecialNewsBoxData;
  topPictureBoxData: PictureBoxData;
}

export default function HomePageTemplate(props: HomePageServerProps) {
  useMemoryMode();
  return (
    <div>
      <Head>
        <title>中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <LSlot>
            <PictureBox data={props.topPictureBoxData} />
          </LSlot>
          <LSlot>
            <Headline data={props.headlineData} />
          </LSlot>
          <LSlot>
            <HomeCarousel />
          </LSlot>
        </LLanding>
        <LContainer>
          <LLeftCol>
            <HomePageNewsListBox />
          </LLeftCol>
          <LRightCol>
            <LSlot>
              <SpecialNewsBox data={props.specialNewsBoxData} />
            </LSlot>
            <LSlot>
              <HotListBox data={props.hotListBoxData} />
            </LSlot>
            <LSlot>
              <TopicBox />
            </LSlot>
            <LSlot>
              <BooksShowBox data={props.booksShowBoxData} />
            </LSlot>
            <LSlot>
              <PictureBox data={props.leftTopPictureBoxData} />
            </LSlot>
            <LSlot>
              <PictureBox data={props.leftBottomPictureBoxData} />
            </LSlot>
          </LRightCol>
        </LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<HomePageServerProps> = async () => {
  return {
    props: {
      booksShowBoxData: HomePageDebugData.booksShowBoxData,
      headlineData: HomePageDebugData.headlineData,
      hotListBoxData: HomePageDebugData.hotListBoxData,
      leftBottomPictureBoxData: HomePageDebugData.leftBottomPictureBoxData,
      leftTopPictureBoxData: HomePageDebugData.leftTopPictureBoxData,
      specialNewsBoxData: HomePageDebugData.specialNewsBoxData,
      topPictureBoxData: HomePageDebugData.topPictureBoxData,
    },
  };
};
