import Head from 'next/head';
import { LBackground, LFooter, LHeader, LLanding, LMain } from '@/layouts/index';
import { Navigation, HeaderBackground, ScrollToTop, TopBar, Footer } from '@/views/Common';
import { TopicCard, TopicContentNewsList } from './components';

export default function TopicContentPageTemplate() {
  return (
    <>
      <Head>
        <title>河南戏剧 话题 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LBackground>
        <HeaderBackground />
      </LBackground>
      <LMain>
        <LLanding>
          <TopicCard />
        </LLanding>
        <LLanding>
          <TopicContentNewsList />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </>
  );
}
