import Head from 'next/head';
import { ColumnContentArticleList, ColumnContentHotList, ColumnContentVideoList } from './components';
import { Divider } from '@arco-design/web-react';
import { LContainer, LFooter, LHeader, LLanding, LMain } from '@/layouts/index';
import { Footer, Navigation, ScrollToTop, TopBar } from '@/views/Common';

export default function ColumnContentPageTemplate() {
  return (
    <>
      <Head>
        <title>社会 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <h2 className="text-2xl font-bold text-red-700">社会</h2>
          <Divider />
        </LLanding>
        <LLanding>
          <ColumnContentHotList />
        </LLanding>
        <Divider />
        <LLanding>
          <ColumnContentArticleList />
        </LLanding>
        <Divider />
        <LLanding>
          <ColumnContentVideoList />
        </LLanding>
        <LContainer></LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </>
  );
}
