import Head from 'next/head';
import { ArticleNextListBox } from '../../components/ArticleContentPage/ArticleNextListBox';
import { ArticleReader } from '../../components/ArticleContentPage/ArticleReader';
import { BooksShowBox } from '../../components/HomePage/BooksShowBox';
import { TopicBox } from '../../components/HomePage/TopicBox';
import { Footer } from '../../components/Common/Footer';
import { Navigation } from '../../components/Common/Navigation';
import { PictureBox } from '../../components/Common/PictureBox';
import { ScrollToTop } from '../../components/Common/ScrollToTop';
import { TopBar } from '../../components/Common/TopBar';
import { HomePageDebugData } from '../../debug/HomePage';
import { LContainer, LFooter, LHeader, LLeftCol, LMain, LRightCol, LSlot, LStickySlot } from '../../layouts';

export default function ArticleContentPage() {
  return (
    <div>
      <Head>
        <title>中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LContainer>
          <LLeftCol>
            <LSlot>
              <ArticleReader />
            </LSlot>
            <LSlot></LSlot>
          </LLeftCol>
          <LRightCol>
            <LSlot>
              <PictureBox data={HomePageDebugData.leftBottomPictureBoxData}></PictureBox>
            </LSlot>
            <LSlot>
              <BooksShowBox data={HomePageDebugData.booksShowBoxData} />
            </LSlot>
            <LSlot>
              <TopicBox />
            </LSlot>
            <LStickySlot>
              <ArticleNextListBox data={HomePageDebugData.hotListBoxData} />
            </LStickySlot>
          </LRightCol>
        </LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
