import Head from 'next/head';
import { ResourceNotFound } from '../components/ErrorPage/ResourceNotFound';
import { Footer } from '../components/Utils/Footer';
import { Navigation } from '../components/Utils/Navigation';
import { ScrollToTop } from '../components/Utils/ScrollToTop';
import { TopBar } from '../components/Utils/TopBar';
import { LFooter, LHeader, LLanding, LMain } from '../layouts';
export default function Custom404() {
  return (
    <div>
      <Head>
        <title>资源不存在 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <ResourceNotFound />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
