import Head from 'next/head';
import { Footer } from '../components/Utils/Footer';
import { Navigation } from '../components/Utils/Navigation';
import { ScrollToTop } from '../components/Utils/ScrollToTop';
import { TopBar } from '../components/Utils/TopBar';
import { LContainer, LFooter, LHeader, LLanding, LLeftCol, LMain, LRightCol } from '../layouts';
export default function Custom500() {
  return (
    <div>
      <Head>
        <title>服务器发生严重错误 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding></LLanding>
        <LContainer>
          <LLeftCol></LLeftCol>
          <LRightCol></LRightCol>
        </LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
