import { Collapse, Divider } from '@arco-design/web-react';
import Head from 'next/head';
import { HeadlineBar } from '../components/HeadlineBar';
import { HomeCarousel } from '../components/HomeCarousel';
import { HotListBox } from '../components/HotListBox';
import { Navigation } from '../components/Navigation';
import { NewsList } from '../components/HomeNewsList';
import { PictureBox } from '../components/PictureBox';
import { HomeLayout } from '../layouts/HomeLayout';
import { FriendItem, WebsiteSummary } from '../models/data';
import { APIResponse } from '../types/response';
const CollapseItem = Collapse.Item;

interface HomePageServerProps {
  friends: APIResponse<FriendItem[]>;
  website_summary: APIResponse<WebsiteSummary>;
}

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout.Header>
        <Navigation />
      </HomeLayout.Header>
      <HomeLayout.Main>
        <HomeLayout.Landing>
          <PictureBox
            src={
              'https://oss-alpha-static-zaobao.oss-cn-hongkong.aliyuncs.com/assets/common/imgs/china-20-entry-banner/banner_pc.png'
            }
          />
          <HeadlineBar />
          <HomeCarousel />
          
        </HomeLayout.Landing>
        <HomeLayout.Container>
          <HomeLayout.LeftSlot>
            <NewsList />
          </HomeLayout.LeftSlot>
          <HomeLayout.RightSlot>
            <HotListBox/>
          </HomeLayout.RightSlot>
        </HomeLayout.Container>
      </HomeLayout.Main>
    </div>
  );
}

// export const getServerSideProps: GetServerSideProps<HomePageServerProps> = async () => {
//   return { props: {} };
// };
