import Head from 'next/head';
import { BooksShowBox } from '../components/BooksShowBox';
import { HomeCarousel } from '../components/CarouselBox';
import { Footer } from '../components/Footer';
import { HeadlineBar } from '../components/HeadlineBar';
import { NewsList } from '../components/HomeNewsList';
import { HotListBox } from '../components/HotListBox';
import { Navigation } from '../components/Navigation';
import { PictureBox } from '../components/PictureBox';
import { SpecialNewsBox } from '../components/SpecialNewsBox';
import { TopicBox } from '../components/TopicBox';
import { HomeLayout } from '../layouts/HomeLayout';
import { FriendItem, WebsiteSummary } from '../models/data';
import { APIResponse } from '../types/response';

const LHeader = HomeLayout.Header;
const LMain = HomeLayout.Main;
const LFooter = HomeLayout.Footer;
const LLanding = HomeLayout.Landing;
const LContainer = HomeLayout.Container;
const LLeftCol = HomeLayout.LeftCol;
const LRightCol = HomeLayout.RightCol;
const LSlot = HomeLayout.Slot;

interface HomePageServerProps {
  friends: APIResponse<FriendItem[]>;
  website_summary: APIResponse<WebsiteSummary>;
}

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <LSlot>
            <PictureBox src="https://oss-alpha-static-zaobao.oss-cn-hongkong.aliyuncs.com/assets/common/imgs/china-20-entry-banner/banner_pc.png" />
          </LSlot>
          <LSlot>
            <HeadlineBar />
          </LSlot>
          <LSlot>
            <HomeCarousel />
          </LSlot>
        </LLanding>
        <LContainer>
          <LLeftCol>
            <NewsList />
          </LLeftCol>
          <LRightCol>
            <LSlot>
              <SpecialNewsBox />
            </LSlot>
            <LSlot>
              <HotListBox />
            </LSlot>
            <LSlot>
              <TopicBox />
            </LSlot>
            <LSlot>
              <BooksShowBox />
            </LSlot>
            <LSlot>
              <PictureBox src="https://oss-alpha-static-zaobao.oss-cn-hongkong.aliyuncs.com/s3fs-public/styles/article_large_full/public/2022-10/2022-10-05t043447z_921512572_rc2xqs933lto_rtrmadp_3_taiwan-economy-chips_0.jpg?2778123" />
            </LSlot>
            <LSlot>
              <PictureBox src="https://oss-alpha-static-zaobao.oss-cn-hongkong.aliyuncs.com/s3fs-public/styles/article_large_crop/public/2022-10/ZB_1030_CJ_doc7ncuxlsoltk11saozcrd_29183017_chngmj.jpg?2778524" />
            </LSlot>
          </LRightCol>
        </LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
    </div>
  );
}

// export const getServerSideProps: GetServerSideProps<HomePageServerProps> = async () => {
//   return { props: {} };
// };
