import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { BooksShowBox } from './components/BooksShowBox';
import { Headline } from './components/Headline';
import useMemoryMode from 'hooks/useMemoryMode';
import { LContainer, LFooter, LHeader, LLanding, LLeftCol, LMain, LRightCol, LSlot } from '@layouts/index';
import { BooksShowBoxData, HeadlineData, HotListBoxData, PictureBoxData, SpecialNewsBoxData } from '@models/data';
import Footer from '@arco-design/web-react/es/Layout/footer';
import { HomePageDebugData } from '@debug/HomePage';
import { HomeCarousel } from 'components/Common/CarouselBox';
import { HotListBox } from 'components/Common/HotListBox';
import { Navigation } from 'components/Common/Navigation';
import { PictureBox } from 'components/Common/PictureBox';
import { ScrollToTop } from 'components/Common/ScrollToTop';
import { TopBar } from 'components/Common/TopBar';
import { TopicBox } from 'components/Common/TopicBox';
import { HomePageNewsListBox } from './components/HomePageNewsListBox';
import { SpecialNewsBox } from './components/SpecialNewsBox';

export interface HomePageServerProps {
  booksShowBoxData: BooksShowBoxData;
  headlineData: HeadlineData;
  hotListBoxData: HotListBoxData;
  leftBottomPictureBoxData: PictureBoxData;
  leftTopPictureBoxData: PictureBoxData;
  specialNewsBoxData: SpecialNewsBoxData;
  topPictureBoxData: PictureBoxData;
}

export default function HomePageTemplate(props: HomePageServerProps) {
  useMemoryMode();
  return (
    <div>
      <Head>
        <title>中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <LSlot>
            <PictureBox data={props.topPictureBoxData} />
          </LSlot>
          <LSlot>
            <Headline data={props.headlineData} />
          </LSlot>
          <LSlot>
            <HomeCarousel />
          </LSlot>
        </LLanding>
        <LContainer>
          <LLeftCol>
            <HomePageNewsListBox />
          </LLeftCol>
          <LRightCol>
            <LSlot>
              <SpecialNewsBox data={props.specialNewsBoxData} />
            </LSlot>
            <LSlot>
              <HotListBox data={props.hotListBoxData} />
            </LSlot>
            <LSlot>
              <TopicBox />
            </LSlot>
            <LSlot>
              <BooksShowBox data={props.booksShowBoxData} />
            </LSlot>
            <LSlot>
              <PictureBox data={props.leftTopPictureBoxData} />
            </LSlot>
            <LSlot>
              <PictureBox data={props.leftBottomPictureBoxData} />
            </LSlot>
          </LRightCol>
        </LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<HomePageServerProps> = async () => {
  return {
    props: {
      booksShowBoxData: HomePageDebugData.booksShowBoxData,
      headlineData: HomePageDebugData.headlineData,
      hotListBoxData: HomePageDebugData.hotListBoxData,
      leftBottomPictureBoxData: HomePageDebugData.leftBottomPictureBoxData,
      leftTopPictureBoxData: HomePageDebugData.leftTopPictureBoxData,
      specialNewsBoxData: HomePageDebugData.specialNewsBoxData,
      topPictureBoxData: HomePageDebugData.topPictureBoxData,
    },
  };
};
