import Footer from '@arco-design/web-react/es/Layout/footer';
import Head from 'next/head';
import { LBackground, LFooter, LHeader, LLanding, LMain } from 'layouts';
import { Navigation } from 'components/Common/Navigation';
import { PageHeaderBackground } from 'components/Common/PageHeaderBackground';
import { ScrollToTop } from 'components/Common/ScrollToTop';
import { TopBar } from 'components/Common/TopBar';
import { TopicCard } from 'components/TopicContentPage/components/TopicCard';
import { TopicContentNewsList } from 'components/TopicContentPage/components/TopicContentNewsList';

export default function TopicContentPageTemplate() {
  return (
    <div>
      <Head>
        <title>河南戏剧 话题 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LBackground>
        <PageHeaderBackground />
      </LBackground>
      <LMain>
        <LLanding>
          <TopicCard />
        </LLanding>
        <LLanding>
          <TopicContentNewsList />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
