import Head from 'next/head';
import { TopicCard } from '../../components/TopicContentPage/TopicCard';
import { TopicContentNewsList } from '../../components/TopicContentPage/TopicContentNewsList';
import { Footer } from '../../components/Common/Footer';
import { Navigation } from '../../components/Common/Navigation';
import { PageHeaderBackground } from '../../components/Common/PageHeaderBackground';
import { ScrollToTop } from '../../components/Common/ScrollToTop';
import { TopBar } from '../../components/Common/TopBar';
import { LBackground, LContainer, LFooter, LHeader, LLanding, LLeftCol, LMain, LSlot } from '../../layouts';

export default function TopicContentPage() {
  return (
    <div>
      <Head>
        <title>河南戏剧 话题 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LBackground>
        <PageHeaderBackground />
      </LBackground>
      <LMain>
        <LLanding>
          <TopicCard />
        </LLanding>
        <LLanding>
          <TopicContentNewsList />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
