import Head from 'next/head';
import { TopicNewsList } from '../../components/TopicPage/TopicNewsList';
import { Footer } from '../../components/Utils/Footer';
import { Navigation } from '../../components/Utils/Navigation';
import { ScrollToTop } from '../../components/Utils/ScrollToTop';
import { TopBar } from '../../components/Utils/TopBar';
import { LFooter, LHeader, LLanding, LMain } from '../../layouts';

export default function TopicPage() {
  return (
    <div>
      <Head>
        <title>话题 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <TopicNewsList />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
