import { LMain } from '@layouts/index';
import dynamic from 'next/dynamic';
import Head from 'next/head';

const DynamicBookReader = dynamic(() => import('./components/BookReader').then((mod) => mod.BookReader), {
  ssr: false,
});

export const BookContentPageTemplate = () => {
  return (
    <div>
      <Head>
        <title>中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LMain>
        <DynamicBookReader />
      </LMain>
    </div>
  );
};
