import { Divider } from '@arco-design/web-react';
import Head from 'next/head';
import { GroupContentArticleList } from '../../components/GroupContentPage/GroupContentArticleList';
import { GroupContentHotList } from '../../components/GroupContentPage/GroupContentHotList';
import { GroupContentVideoList } from '../../components/GroupContentPage/GroupContentVideoList';
import { Footer } from '../../components/Utils/Footer';
import { Navigation } from '../../components/Utils/Navigation';
import { ScrollToTop } from '../../components/Utils/ScrollToTop';
import { TopBar } from '../../components/Utils/TopBar';
import { LContainer, LFooter, LHeader, LLanding, LLeftCol, LMain, LRightCol } from '../../layouts';

export default function GroupContentPage() {
  return (
    <div>
      <Head>
        <title>河南看点 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <GroupContentHotList />
        </LLanding>
        <Divider />
        <LLanding>
          <GroupContentArticleList />
        </LLanding>
        <Divider />
        <LLanding>
          <GroupContentVideoList />
        </LLanding>
        <LContainer></LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
