import { Divider } from '@arco-design/web-react';
import Head from 'next/head';
import GroupPageNewsList from '../../components/GroupPage/GroupPageNewsListBox';
import { Footer } from '../../components/Common/Footer';
import { Navigation } from '../../components/Common/Navigation';
import { ScrollToTop } from '../../components/Common/ScrollToTop';
import { TopBar } from '../../components/Common/TopBar';
import { LFooter, LHeader, LLanding, LMain } from '../../layouts';

export default function GroupPage() {
  return (
    <div>
      <Head>
        <title>{'专栏组 | 中原科技网'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <h1 className="text-xl font-bold">专栏组</h1>
          <Divider />
        </LLanding>
        <LLanding>
          <GroupPageNewsList />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer></Footer>
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
