import { Divider } from '@arco-design/web-react';
import Head from 'next/head';
import { Footer } from '../../components/Utils/Footer';
import GroupPageNewsList from '../../components/GroupPage/GroupPageNewsListBox';
import { Navigation } from '../../components/Utils/Navigation';
import { GroupLayout } from '../../layouts/GroupLayout';
import { ScrollToTop } from '../../components/Utils/ScrollToTop';
const LHeader = GroupLayout.Header;
const LMain = GroupLayout.Main;
const LFooter = GroupLayout.Footer;
const LLanding = GroupLayout.Landing;
const LContainer = GroupLayout.Container;
const LLeftCol = GroupLayout.LeftCol;
const LRightCol = GroupLayout.RightCol;
const LSlot = GroupLayout.Slot;

export default function GroupPage() {
  return (
    <div>
      <Head>
        <title>{'专栏组 | 中原科技网'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <h1 className="text-xl font-bold">专栏组</h1>
          <Divider />
        </LLanding>
        <LLanding>
          <GroupPageNewsList />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer></Footer>
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
