import Footer from '@arco-design/web-react/es/Layout/footer';
import Head from 'next/head';
import { LFooter, LHeader, LLanding, LMain } from 'layouts';
import { Navigation } from 'components/Common/Navigation';
import { ScrollToTop } from 'components/Common/ScrollToTop';
import { TopBar } from 'components/Common/TopBar';
import { TopicNewsList } from './components/TopicNewsList';

export default function TopicIndexPageTemplate() {
  return (
    <div>
      <Head>
        <title>话题 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <LHeader>
        <Navigation />
      </LHeader>
      <LMain>
        <LLanding>
          <TopicNewsList />
        </LLanding>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
      <ScrollToTop />
    </div>
  );
}
