import Head from 'next/head';
import { PageHeaderBackground } from '../../components/Common/PageHeaderBackground';
import { CreatorCard } from '../../components/CreatorProfilePage/CreatorCard';
import { CreatorWorksList } from '../../components/CreatorProfilePage/CreatorNewsList';
import { Footer } from '../../components/Common/Footer';
import { HotListBox } from '../../components/Common/HotListBox';
import { Navigation } from '../../components/Common/Navigation';
import { PictureBox } from '../../components/Common/PictureBox';
import { HomePageDebugData } from '../../debug/HomePage';
import { LBackground, LContainer, LFooter, LHeader, LLeftCol, LMain, LRightCol, LSlot } from '../../layouts';


export default function CreatorProfilePage() {
  return (
    <div>
      <Head>
        <title>张宇腾的创作 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LHeader>
        <Navigation />
      </LHeader>
      <LBackground>
        <PageHeaderBackground />
      </LBackground>
      <LMain>
        <LContainer>
          <LLeftCol>
            <LSlot>
              <CreatorCard />
            </LSlot>
            <LSlot>
              <CreatorWorksList />
            </LSlot>
          </LLeftCol>
          <LRightCol>
            <LSlot>
              <HotListBox data={HomePageDebugData.hotListBoxData} />
            </LSlot>
            <LSlot>
              <PictureBox data={HomePageDebugData.leftBottomPictureBoxData} />
            </LSlot>
            <LSlot>
              <PictureBox data={HomePageDebugData.leftTopPictureBoxData} />
            </LSlot>
          </LRightCol>
        </LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
    </div>
  );
}
