import Head from 'next/head';
import { CreatorBackground } from '../../components/CreatorProfilePage/CreatorBackground';
import { CreatorCard } from '../../components/CreatorProfilePage/CreatorCard';
import { CreatorWorksList } from '../../components/CreatorProfilePage/CreatorNewsList';
import { BooksShowBox } from '../../components/HomePage/BooksShowBox';
import { Footer } from '../../components/Utils/Footer';
import { HotListBox } from '../../components/Utils/HotListBox';
import { Navigation } from '../../components/Utils/Navigation';
import { PictureBox } from '../../components/Utils/PictureBox';
import { HomePageDebugData } from '../../debug/HomePage';
import { CreatorProfileLayout } from '../../layouts/CreatorProfileLayout';
const LHeader = CreatorProfileLayout.Header;
const LMain = CreatorProfileLayout.Main;
const LFooter = CreatorProfileLayout.Footer;
const LLanding = CreatorProfileLayout.Landing;
const LContainer = CreatorProfileLayout.Container;
const LLeftCol = CreatorProfileLayout.LeftCol;
const LRightCol = CreatorProfileLayout.RightCol;
const LSlot = CreatorProfileLayout.Slot;
const LBackground = CreatorProfileLayout.Background;

export default function CreatorProfilePage() {
  return (
    <div>
      <Head>
        <title>张宇腾的创作 | 中原科技网</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LHeader>
        <Navigation />
      </LHeader>
      <LBackground>
        <CreatorBackground />
      </LBackground>
      <LMain>
        <LContainer>
          <LLeftCol>
            <LSlot>
              <CreatorCard />
            </LSlot>
            <LSlot>
              <CreatorWorksList />
            </LSlot>
          </LLeftCol>
          <LRightCol>
            <LSlot>
              <HotListBox data={HomePageDebugData.hotListBoxData} />
            </LSlot>
            <LSlot>
              <PictureBox data={HomePageDebugData.leftBottomPictureBoxData} />
            </LSlot>
            <LSlot>
              <PictureBox data={HomePageDebugData.leftTopPictureBoxData} />
            </LSlot>
          </LRightCol>
        </LContainer>
      </LMain>
      <LFooter>
        <Footer />
      </LFooter>
    </div>
  );
}
